# Generated by Django 5.0.6 on 2024-05-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Введите заголовок",
                        max_length=100,
                        verbose_name="Заголовок",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                (
                    "content",
                    models.TextField(help_text="Введите текст", verbose_name="Текст"),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        help_text="Вставьте изображение",
                        null=True,
                        upload_to="catalog/blog_previews",
                        verbose_name="Изображение",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("published", models.BooleanField(default=False)),
                (
                    "views_count",
                    models.IntegerField(
                        default=0,
                        help_text="Введите количество просмотров",
                        verbose_name="Количество просмотров",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="product",
            name="cost_product",
            field=models.IntegerField(
                help_text="Введите стоимость товара", verbose_name="Стоимость товара"
            ),
        ),
    ]
