# Generated by Django 5.0.6 on 2024-05-15 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_blog_alter_product_cost_product"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={
                "verbose_name": ("Статья блога",),
                "verbose_name_plural": ("Статьи блога",),
            },
        ),
    ]
