# Generated by Django 5.0.6 on 2024-05-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_blog_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="views_count",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                help_text="Введите количество просмотров",
                null=True,
                verbose_name="Количество просмотров",
            ),
        ),
    ]
