# Generated by Django 5.0.6 on 2024-05-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_alter_blog_views_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="published",
            field=models.BooleanField(default=False, verbose_name="Опубликовано"),
        ),
    ]
