# Generated by Django 5.0.6 on 2024-05-18 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_alter_blog_published"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Blog",
        ),
    ]
