# Generated by Django 4.2.2 on 2024-06-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0012_product_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "permissions": [
                    ("can_cancel_publish_product", "Can Cancel Publish Product"),
                    (
                        "can_change_description_product",
                        "Can Change Description Product",
                    ),
                    ("can_change_category_product", "Can Change Category Product"),
                ],
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="Статус публикации"),
        ),
    ]
